plugins {
    id 'com.android.application'
}

android {
    compileSdk 36

    namespace "com.example.flagsgame"

    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

    defaultConfig {
        applicationId "com.example.flagsgame"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.github.dorukkangal:VectorMaster:1.1.4'

    implementation 'androidx.appcompat:appcompat:1.6.1'
//    implementation 'androidx.compose.ui:ui:1.11.0'
    implementation 'androidx.webkit:webkit:1.8.0'
    implementation 'com.google.android.material:material:1.9.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation 'androidx.test:core:1.5.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'androidx.test:core:1.5.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.3'
    testImplementation 'org.json:json:20251224'
    testImplementation 'com.networknt:json-schema-validator:1.0.79'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
}
